
"set smartindent -->  DO NOT ENABLE! starts indenting C keywords in ANY file...
"set cindent        " indent rules for C...
set cinoptions=l1   " otherwise the case statement is wrongly indented (see :help cinoptions-values)
